### ISSUE TITLE
Back link to index retaining worklist

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#57]
Investigate if it is possible to link back to index and remember the user so it shows tickets filtered to the individual rather than unassigned.

**Comment by PangolinPaw** [comment]
By changing the form that controls the 'show closed' and 'assigned to' inputs to a GET (storing the selected values in the URL), PHP in the back.php include file could append the current user's username to the URL it links to:

```
<?php
    echo '<a href="index.php?user=` . get_current_user() . '">Back</a>';
?>
```

Minor complication:
If we change that form to use the URL then the 'show more' button at the bottom of the page will need to be changed so that it doesn't (otherwise each form will overwrite the other's UL parameters and neither will work correctly).

**Comment by Jarlaxle1979** [comment]
@PangolinPaw just to confirm, are you saying that the load more tickets feature needs to be removed and so all tickets assigned will show?

**Comment by PangolinPaw** [comment]
It's possible to keep both, but easier to just remive the 'show more'.  We can always restore it in a later release.

**Comment by Jarlaxle1979** [comment]
@PangolinPaw That's fine by me.  To be honest when working in that view, it can be a bit annoying to have to load more.  There is also a bug with it at the moment so this is the easiest way to fix it!
